Repository vtex-apps/my-account, pull requests merged in 2019-09, with the labels that each got.

#117 Hide MyCards 1.x
  CHANGELOG.md
  graphql/schema.graphql
  manifest.json
  node/index.ts
  node/package.json
  node/resolvers/settings.ts
  node/tsconfig.json
  node/yarn.lock
  package.json
  public/metadata/icon.png
  react/components/Menu/MenuLinksList.tsx
  react/components/Menu/index.tsx
  react/components/Profile/ProfileFormBox.tsx
  react/components/shared/withSettings.tsx
  react/graphql/settings.gql
  react/package.json
Labels: enhancement

#119 Fix country change and geolocation edit + form refactor
  CHANGELOG.md
  node/yarn.lock
  react/components/Addresses/AddressEditor.tsx
  react/components/Addresses/AddressForm.tsx
  react/components/Addresses/AddressFormBox.tsx
  react/components/Addresses/emptyAddress.ts
  react/components/loaders/AddressCreateLoading.tsx
  react/components/loaders/AddressEditLoading.tsx
  react/components/loaders/AddressesLoading.tsx
  react/components/loaders/ProfileEditLoading.tsx
  react/components/loaders/ProfileLoading.tsx
  react/components/pages/AddressCreate.tsx
  react/components/pages/AddressEdit.tsx
  react/components/pages/Addresses.tsx
  react/components/pages/Profile.tsx
  react/components/pages/ProfileEdit.tsx
  react/components/shared/withContentWrapper.tsx
  react/package.json
  react/typings/global.d.ts
  react/typings/vtex.address-form/components.d.ts
  react/typings/vtex.address-form/helpers.d.ts
  react/yarn.lock
Labels: bug, enhancement

#122 Fix profile photo plus sign button size on Safari
  CHANGELOG.md
  react/components/Menu/ProfilePicture/UserPicture.tsx
Labels: bug
